---
- name: Install python
  apt: name={{item}} state=installed
  with_items:
    - python
    - python-pip
    - virtualenv

- name: Install development tools
  apt: name={{item}} state=installed
  with_items:
    - git
    - vim
