---
- name: Fetch ugcal
  register: ugcalinstalled
  git: repo={{ repository }}
       dest={{ install_path }}

- name: Install ugcal requirements
  pip:
    requirements={{ install_path }}/requirements.txt
    virtualenv={{ install_path }}/env

- name: Setup ugcal cron
  when: ugcalinstalled|success
  cron: name="run-ugcal-cron" user=pi minute="1" hour="*/4" job="cd {{ install_path }}; {{ install_path }}/env/bin/python -m ugcal.ugcal 2>&1 | logger"
